apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagamentos-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pagamentos
  template:
    metadata:
      labels:
        app: pagamentos
    spec:
      containers:
        - name: pagamentos
          image: luiza/pagamentos-service:v1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: pagamentos-config
                  key: db_host
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
